DB_FILENAME = "blockchain.db"

GENESIS_BLOCK = "GENESIS-BLOCK"
STORAGE_VALUE = 100
GENESIS_REWARD = 100
STORAGE_CHAIN = "STORAGE-CHAIN"

DIFFICULTY = 20

RANDOM_BYTES = 32
START_PERCENT = 10
STORAGE_REWARD = 1

TXS_LIMIT = 2
